name: ğŸ’» Test code validation

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: ï¸ğŸ‘¶ Unit Test with Gradle
        run: ./gradlew --console verbose clean unitTestCoverage
      - name: mv for separate report folder
        run: mv ./build/reports/jacoco/test ./build/reports/jacoco/unitTest
      - name: mv for separate report name
        run: mv ./build/reports/jacoco/unitTest/jacocoTestReport.xml ./build/reports/jacoco/unitTest/unitTestReport.xml
      - name: ğŸ“² Upload unitTest coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./build/reports/jacoco/unitTest/unitTestReport.xml
          flags: unitTest
          name: codecov-unit
          verbose: true
      - name: ğŸ‘¨â€ğŸ‘¨â€ğŸ‘§â€ğŸ‘¦ Integration Test with Gradle
        run: ./gradlew --console verbose clean integrationTestCoverage
      - name: ğŸ“² Upload integrationTest coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./build/reports/jacoco/test/jacocoTestReport.xml
          flags: integrationTest
          name: codecov-integration
          verbose: true
